embedding_model: nomic-embed-text
llm_model: llama3.2
chroma_collection_name: rag-chroma-collection
chunk_size: 1000
chunk_overlap: 200
retriever_k: 4
system_prompt: |
  Answer the user's questions based on the below context. Also provide the source document for each piece of information:

  {context}
retriever_prompt: |
  Given the above conversation, generate a search query to look up in order to get information relevant to the conversation
